/*
This is an auto-generated code file. It is not recommended that you attempt to edit it as any
changes will be overwritten during the course of configuration of the BreadAI tool.
If compilation errors are being caused by this class, .

Version: Pre-Alpha
Generated: 8/19/2023 12:27:58 AM
*/

public static class AutoGenerated_Enums
{
    /// <summary>
    /// Enum with all Bread AI Interfaces, which are defined as interfaces with the BreadInterface attribute.
    /// </summary>
    public enum AIInterfaces
    {
        IUseMeshRenderer,
        IUseRigidbody,
        IUseSightBox,
        IAmAlive,
        IAmImmuneToTargetingByTentacles,
        ICanBeDamaged,
        ICanBeDigested,
        ICanDie,
        ICanGainNutrition,
        ICanSee,
        IHaveDigestDamageDealt,
        IHaveEyes,
        IHaveGrowthSpeed,
        IHaveHitPoints,
        IHaveMass,
        IHaveMassPerCubicFoot,
        IHaveMaxTentacles,
        IHaveMoveSpeed,
        IHaveNutrition,
        IHaveRotateSpeed,
        IHaveSuckSpeed,
        IHaveTentacleHitSpeed,
        IHaveTentacleReach,
        IHaveThingsInMyStomach,
        IHaveThingsSeen,
    }


}