using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public class DynamicCode
{
    // The warning message that is prepended to each auto-generated code file.
    private static string AutoGeneratedWarning =>
        "/*\n" +
        "This is an auto-generated code file. It is not recommended that you attempt to edit it as any\n" +
        "changes will be overwritten during the course of configuration of the BreadAI tool.\n" +
        "If compilation errors are being caused by this class, .\n" +
        "\nVersion: Pre-Alpha\n" +
        $"Generated: {DateTime.Now}\n" +
        "*/\n\n";

    // Unity menu item to generate enums for Bread AI.
    [MenuItem("Assets/AutoGenerate/AIInterfaces", false, priority: 0)]
    public static void DynamicallyGenerateAIInterfaces()
    {
        if (AIBakerData.instance.BreadInterfaces.Keys.Count == 0)
        {
            Debug.LogError($"No data baked for BreadInterfaces! {System.Reflection.MethodBase.GetCurrentMethod().Name} failed!");
            return;
        }

        // Build the content for enums.
        string enumContent = GenerateEnumContent("AIInterfaces", "Enum with all Bread AI Interfaces, which are defined as interfaces with the BreadInterface attribute.");

        // You can continue building other enum contents here, such as "AIData" and "AIMethods".

        string fileContent = GenerateFileContent(enumContent, true, true, "AutoGenerated_Enums");
        WriteToFile("Assets/BreadAI/Reflection/GeneratedCode/InterfacesEnum.cs", fileContent);
    }

    // Method to generate the content of a specific enum with the given name and summary.
    private static string GenerateEnumContent(string enumName, string summary)
    {
        string content = $"\t/// <summary>\n\t/// {summary}\n\t/// </summary>\n";
        content += $"\tpublic enum {enumName}\n\t{{\n";
        foreach (var key in AIBakerData.instance.BreadInterfaces.Keys)
        {
            content += $"\t\t{key},\n";
        }
        content += "\t}\n\n"; // Adding a line break between enums.
        return content;
    }

    // Generate the full content of the class file, including all enums.
    private static string GenerateFileContent(string content, bool isPublic, bool isStatic, string className)
    {
        string accessModifier = isPublic ? "public" : "internal";
        string staticModifier = isStatic ? "static " : string.Empty;

        return AutoGeneratedWarning +
               $"{accessModifier} {staticModifier}class {className}\n{{\n" +
               $"{content}\n" +
               "}";
    }

    // Write the generated content to a file.
    private static void WriteToFile(string filePath, string content)
    {
        File.WriteAllText(Path.Combine(filePath), content);
    }



}
