/*
This is an auto-generated code file. It is not recommended that you attempt to edit it as any
changes will be overwritten during the course of configuration of the BreadAI tool.

Version: Pre-Alpha
Generated: 8/18/2023 11:30:02 AM
*/

public static class AutoGenerated_Enums
{
    /// <summary>
    /// Enum with all Bread AI Interfaces, which are defined as interfaces 
	/// with the BreadInterface attribute.
    /// </summary>
    public enum AIInterfaces
	{
		IUseMeshRenderer,
		IUseRigidbody,
		IUseSightBox,
		IAmAlive,
		IAmImmuneToTargetingByTentacles,
		ICanBeDamaged,
		ICanBeDigested,
		ICanDie,
		ICanGainNutrition,
		ICanSee,
		IHaveDigestDamageDealt,
		IHaveEyes,
		IHaveGrowthSpeed,
		IHaveHitPoints,
		IHaveMass,
		IHaveMassPerCubicFoot,
		IHaveMaxTentacles,
		IHaveMoveSpeed,
		IHaveNutrition,
		IHaveRotateSpeed,
		IHaveSuckSpeed,
		IHaveTentacleHitSpeed,
		IHaveTentacleReach,
		IHaveThingsInMyStomach,
		IHaveThingsSeen,
	}

	/// <summary>
    /// Enum with all Bread AI Data Members, which are defined as fields or properties which 
	/// are defined within a Bread AI Interface
	/// </summary>
	public enum AIData
	{
		MyMeshRenderer,
		MyRigidbody,
		MySightBox,
		ThingsNearby,
		ThingsNearbyFilter,
		IsAlive,
		SightDistance,
		OnlySeeMask,
		ThingsSeen,
		DigestDamageDealt,
		DamageType,
		Eyes,
		GrowthSpeed,
		HitPoints,
		Mass,
		MassPerCubicFoot,
		MaxTentacles,
		MoveSpeed,
		Nutrition,
		RotateSpeed,
		SuckSpeed,
		TentacleHitSpeed,
		MinTentacleReach,
		MaxTentacleReach,
		DragInsideStomach,
		AngularDragInsideStomach,
	}


    /// <summary>
    /// Enum with all Bread AI Methods, which are defined as methods or functions which 
    /// are defined within a Bread AI Interface
    /// </summary>
    public enum AIMethods
	{
		BeDamaged,
		BeDigested,
		Die,
		GainNutrition,
	}

}